# Generated by Django 5.1.1 on 2024-09-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tbl_login_flag_tbl_login_post_tbl_login_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('mobile_no', models.CharField(max_length=13)),
                ('class_name', models.CharField(max_length=20)),
                ('div', models.CharField(max_length=20)),
                ('batch', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=128)),
                ('security_question', models.CharField(max_length=128)),
                ('security_question_ans', models.CharField(max_length=128)),
                ('flag', models.CharField(max_length=20)),
            ],
        ),
    ]
