# Generated by Django 5.1.1 on 2024-09-29 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_tbl_teachers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_login',
            name='verify_status',
        ),
        migrations.AddField(
            model_name='tbl_teachers',
            name='post',
            field=models.CharField(default='default_post', max_length=50),
        ),
        migrations.AlterField(
            model_name='tbl_login',
            name='flag',
            field=models.CharField(max_length=20),
        ),
    ]
