# Generated by Django 5.1.1 on 2024-09-29 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_tbl_login_verify_status_tbl_teachers_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_teachers',
            name='login',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='api.tbl_login'),
        ),
    ]
