# Generated by Django 5.1.1 on 2024-09-29 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_tbl_teachers_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_teachers',
            name='login',
        ),
        migrations.AddField(
            model_name='tbl_teachers',
            name='login_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='api.tbl_login'),
        ),
    ]
