# Generated by Django 5.1.1 on 2024-09-29 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_tbl_teachers_login_tbl_teachers_login_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_teachers',
            name='login_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='api.tbl_login'),
        ),
    ]
