# Generated by Django 5.1.1 on 2024-10-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_tbl_teachers_login_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_teachers',
            name='flag',
        ),
        migrations.RemoveField(
            model_name='tbl_teachers',
            name='password',
        ),
        migrations.RemoveField(
            model_name='tbl_teachers',
            name='post',
        ),
        migrations.RemoveField(
            model_name='tbl_teachers',
            name='security_question',
        ),
        migrations.RemoveField(
            model_name='tbl_teachers',
            name='security_question_ans',
        ),
        migrations.RemoveField(
            model_name='tbl_teachers',
            name='username',
        ),
        migrations.AddField(
            model_name='tbl_login',
            name='security_question',
            field=models.CharField(default='default_que', max_length=128),
        ),
        migrations.AddField(
            model_name='tbl_login',
            name='security_question_ans',
            field=models.CharField(default='default_ans', max_length=128),
        ),
        migrations.AlterField(
            model_name='tbl_teachers',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tbl_teachers',
            name='mobile_no',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
