# Generated by Django 5.1.1 on 2024-10-02 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_tbl_teachers_flag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_login',
            name='security_question',
            field=models.CharField(default='default_security_question', max_length=128),
        ),
        migrations.AlterField(
            model_name='tbl_login',
            name='security_question_ans',
            field=models.CharField(default='default_security_question_ans', max_length=128),
        ),
    ]
