# Generated by Django 5.1.1 on 2024-10-06 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_tbl_login_security_question_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_no', models.IntegerField()),
                ('roll_no', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=20)),
                ('div', models.CharField(max_length=20)),
                ('batch', models.CharField(max_length=20)),
                ('group_no', models.IntegerField()),
                ('login_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='api.tbl_login')),
                ('names', models.ManyToManyField(to='api.tbl_student')),
            ],
        ),
    ]
