# Generated by Django 5.1.1 on 2024-10-06 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_tbl_student_tbl_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_students',
            name='names',
        ),
        migrations.AddField(
            model_name='tbl_student',
            name='student_group',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='student_names', to='api.tbl_students'),
        ),
    ]
