# Generated by Django 5.1.1 on 2024-10-06 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_tbl_students_names_tbl_student_student_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_student',
            name='student_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_names', to='api.tbl_students'),
        ),
    ]
