# Generated by Django 5.1.1 on 2024-10-08 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_tbl_student_student_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_students',
            name='enrollment_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tbl_students',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='tbl_students',
            name='roll_no',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='tbl_student',
        ),
    ]
