# Generated by Django 5.1.1 on 2024-10-13 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_tbl_students_enrollment_no_tbl_students_name_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tbl_students',
            constraint=models.UniqueConstraint(fields=('group_no', 'enrollment_no', 'roll_no'), name='unique_student_group'),
        ),
    ]
