# Generated by Django 5.1.1 on 2024-10-14 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_tbl_students_unique_student_group'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tbl_students',
            name='unique_student_group',
        ),
        migrations.AddConstraint(
            model_name='tbl_students',
            constraint=models.UniqueConstraint(fields=('enrollment_no',), name='unique_enrollment_no'),
        ),
        migrations.AddConstraint(
            model_name='tbl_students',
            constraint=models.UniqueConstraint(fields=('batch', 'group_no'), name='unique_group_no_in_batch'),
        ),
    ]
