# Generated by Django 5.1.1 on 2024-10-14 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_tbl_students_unique_student_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_students',
            name='enrollment_no',
            field=models.CharField(max_length=50),
        ),
    ]
