# Generated by Django 5.1.1 on 2024-10-14 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_tbl_students_enrollment_no'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tbl_students',
            constraint=models.UniqueConstraint(fields=('batch', 'group_no', 'enrollment_no'), name='unique_student_in_batch'),
        ),
    ]
