# Generated by Django 5.1.1 on 2024-10-17 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_tbl_students_unique_student_in_batch'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tbl_students',
            name='unique_student_in_batch',
        ),
        migrations.AddConstraint(
            model_name='tbl_students',
            constraint=models.UniqueConstraint(fields=('class_name', 'div', 'batch', 'roll_no'), name='unique_roll_no_in_class_div_batch'),
        ),
    ]
