# Generated by Django 5.1.1 on 2024-10-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_tbl_students_unique_student_in_batch_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tbl_students',
            name='unique_enrollment_no',
        ),
        migrations.RemoveConstraint(
            model_name='tbl_students',
            name='unique_roll_no_in_class_div_batch',
        ),
        migrations.AlterField(
            model_name='tbl_students',
            name='enrollment_no',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
