# Generated by Django 5.1.1 on 2024-10-18 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_tbl_students_unique_enrollment_no_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tbl_students',
            name='unique_group_no_in_batch',
        ),
        migrations.AlterField(
            model_name='tbl_students',
            name='enrollment_no',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='tbl_students',
            constraint=models.UniqueConstraint(fields=('enrollment_no',), name='unique_enrollment_no'),
        ),
        migrations.AddConstraint(
            model_name='tbl_students',
            constraint=models.UniqueConstraint(fields=('login_id', 'batch', 'group_no'), name='unique_group_no_in_batch_for_login'),
        ),
        migrations.AddConstraint(
            model_name='tbl_students',
            constraint=models.UniqueConstraint(fields=('batch', 'group_no', 'enrollment_no'), name='unique_student_in_batch'),
        ),
    ]
