# Generated by Django 5.1.1 on 2024-10-20 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_tbl_students_unique_group_no_in_batch_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tbl_students',
            name='unique_group_no_in_batch_for_login',
        ),
        migrations.RemoveConstraint(
            model_name='tbl_students',
            name='unique_student_in_batch',
        ),
    ]
