# Generated by Django 5.1.1 on 2024-11-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_tbl_students_unique_group_no_in_batch_for_login_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=150)),
                ('task_description', models.CharField(max_length=255)),
                ('assignto', models.CharField(max_length=150)),
                ('due_date', models.DateField(default='')),
            ],
        ),
    ]
