# Generated by Django 5.1.1 on 2024-11-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_task_tbl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_tbl',
            name='assignto',
            field=models.DateField(default=''),
        ),
    ]
