# Generated by Django 5.1.1 on 2024-11-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_task_tbl_assignto'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=20)),
                ('flag', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=20)),
                ('flag', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_div',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=20)),
                ('flag', models.CharField(max_length=20)),
            ],
        ),
    ]
