# Generated by Django 5.1.1 on 2024-11-25 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_tbl_batch_tbl_class_tbl_div'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_batch',
            old_name='class_name',
            new_name='batch_name',
        ),
        migrations.RenameField(
            model_name='tbl_div',
            old_name='class_name',
            new_name='div_name',
        ),
    ]
