# Generated by Django 5.1.1 on 2024-11-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_rename_class_name_tbl_batch_batch_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_batch',
            name='flag',
            field=models.CharField(default='active'),
        ),
        migrations.AlterField(
            model_name='tbl_class',
            name='flag',
            field=models.CharField(default='active'),
        ),
        migrations.AlterField(
            model_name='tbl_div',
            name='flag',
            field=models.CharField(default='active'),
        ),
    ]
